const assert = require('node:assert/strict');
process.env.ETRAI_TEST_MODE = 'mock';
const { contextualClaimText, verificationContext } = require('../src/services/articleContext');
const { buildSearchRepresentation, generateMultiPerspectiveQueries } = require('../src/services/factVerifier');
const claim = { text: 'The chain has seven facilities in the vicinity.', sourceContext: { previousSentence: 'Police identified Sudhanshu as an operator with the Hostel Daze chain.' } };
const expanded = contextualClaimText(claim);
assert(expanded.includes('Hostel Daze'));
assert(expanded.endsWith(claim.text));
assert.equal(claim.text, 'The chain has seven facilities in the vicinity.');
const queries = generateMultiPerspectiveQueries(buildSearchRepresentation(claim));
assert.equal(queries[0].query, claim.text);
assert(queries.some(q => q.strategy === 'local_context' && q.query.includes('Hostel Daze') && q.query.includes('seven facilities')));
assert.equal(JSON.parse(verificationContext(claim)).contextualReading, expanded);
const independent = { text: 'Acme Bank reported annual revenue of 500 million dollars.', sourceContext: claim.sourceContext };
assert.equal(contextualClaimText(independent), independent.text);
assert.equal(contextualClaimText({text: claim.text}), claim.text);
const eventAnchored = contextualClaimText({ text: 'The PG had eight rooms and 16 beds.', articleContext: { headline: 'Seven killed in Satya Niketan hostel collapse', entities: ['Hostel Daze', 'Satya Niketan'] } });
assert(eventAnchored.includes('Satya Niketan hostel collapse'));
const anchoredQueries = generateMultiPerspectiveQueries(buildSearchRepresentation({ text: 'The PG had eight rooms and 16 beds.', articleContext: { headline: 'Hostel Daze building collapse in Satya Niketan', mainEvent: 'Delhi hostel collapse', entities: ['Hostel Daze', 'Satya Niketan'] } }));
assert(anchoredQueries.some(q => q.strategy === 'required_detail' && q.query.includes('Hostel Daze') && q.query.includes('room')));
console.log('Contextual claim search regressions passed.');
